# Setup
title:               Jash Rathod
tagline:             'A Blog for Books'
description:         'Love for books. <br/> Made by <a href="https://twitter.com/rathod_jash" target="_blank">@rathod_jash</a>.'
url:                 https://jashrathod.github.io/book-blog
baseurl:             '/book-blog'
paginate:            10
permalink:           pretty

# About/contact
author:
  name:              Jash Rathod
  url:               https://twitter.com/rathod_jash

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
